### ISSUE TITLE
卸载插件后无法启动nonebot

### ISSUE THREAD

**Issue by rockqtmh** [noneplugin/nonebot-plugin-chess#3]
使用nb plugin 卸载插件后无法启动nonebot，报错信息如下：

11-18 12:47:27 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\base.py", line 254, in _catch_revision_errors
    yield
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\base.py", line 317, in get_revisions
    self.revision_map.get_revisions(id_),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\revision.py", line 542, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
                ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\revision.py", line 565, in get_revisions
    return tuple(
        self._revision_for_ident(rev_id, branch_label)
        for rev_id in resolved_id
    )
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\revision.py", line 566, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\revision.py", line 637, in _revision_for_ident
    raise ResolutionError(
    ...<11 lines>...
    )
alembic.script.revision.ResolutionError: No such revision or branch '32c01e50814d'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\nonebot\bot\.venv\Lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Program Files\Python\Python313\Lib\contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 155, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 66, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 55, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot_plugin_orm\__init__.py", line 84, in init_orm
    await greenlet_spawn(migrate.check, alembic_config)
  File "C:\nonebot\bot\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 201, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot_plugin_orm\migrate.py", line 567, in check
    script.run_env()
    ~~~~~~~~~~~~~~^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\base.py", line 586, in run_env
    util.load_python_file(self.dir, "env.py")
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 90, in <module>
    await_only(coro)
    ~~~~~~~~~~^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 79, in run_migrations_online
    await connection.run_sync(do_run_migrations)
  File "C:\nonebot\bot\.venv\Lib\site-packages\sqlalchemy\ext\asyncio\engine.py", line 886, in run_sync
    return await greenlet_spawn(
           ^^^^^^^^^^^^^^^^^^^^^
        fn, self._proxied, *arg, _require_await=False, **kw
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\nonebot\bot\.venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot_plugin_orm\templates\generic\env.py", line 69, in do_run_migrations
    context.run_migrations()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 8, in run_migrations
    driver = nonebot.get_driver()
               ~~~~~~~~~~~~~~~~^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\runtime\environment.py", line 946, in run_migrations
    self.get_context().run_migrations(**kw)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\runtime\migration.py", line 611, in run_migrations
    for step in self._migrations_fn(heads, self):
                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\nonebot_plugin_orm\migrate.py", line 552, in retrieve_migrations
    if set(script.get_revisions(rev)) != set(script.get_revisions("heads")):
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\base.py", line 314, in get_revisions
    with self._catch_revision_errors():
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\nonebot\bot\.venv\Lib\site-packages\alembic\script\base.py", line 286, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by '32c01e50814d'

**Comment by MeetWq** [comment]
找到 nonebot-plugin-orm 的数据库文件，默认位置在
`C:\Users\<username>\AppData\Local\nonebot2\nonebot-plugin-orm\db.sqlite3`

把 `alembic_version` 表里面的 `32c01e50814d` 删了

![Snipaste_2024-11-18_15-33-01](https://github.com/user-attachments/assets/c37faff7-9554-46f8-8d0f-bd4c949f0e0b)

**Comment by rockqtmh** [comment]
我已经删了，可以解决这个问题。只是反馈下看能不能卸载的时候自动删表。

**Comment by MeetWq** [comment]
这是 nonebot-plugin-orm 的问题，目前他的解决方案是把运行过的迁移脚本复制一份，在 `C:\Users\<username>\AppData\Local\nonebot2\nonebot-plugin-orm\migrations` 下面，这样插件卸载后就不会找不到迁移脚本了
还出现这个报错可能是你之前装这个插件的时候 nonebot-plugin-orm 还没更新

**Comment by rockqtmh** [comment]
好的，谢谢
