### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Amoslzh** [noneplugin/nonebot-plugin-chess#5]
Task exception was never retrieved
future: <Task finished name='Task-41' coro=<Connection.run() done, defined at D:\anaconda3\lib\site-packages\playwright\_impl\_connection.py:174> exception=NotImplementedError()>
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 181, in run
    await self._transport.connect()
  File "D:\anaconda3\lib\site-packages\playwright\_impl\_transport.py", line 136, in connect
    raise exc
  File "D:\anaconda3\lib\site-packages\playwright\_impl\_transport.py", line 124, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\anaconda3\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\anaconda3\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\anaconda3\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\bilibili_api\utils\network.py", line 26, in __clean
    loop = asyncio.get_event_loop()
  File "D:\anaconda3\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by MeetWq** [comment]
你是pip装的吗？
可以pip list看一次 uvicorn 和 nonebot_plugin_htmlrender 的版本

**Comment by Amoslzh** [comment]
看过了 版本都是对的。下面还有个错误
05-04 00:02:22 [ERROR] uvicorn | Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "D:\anaconda3\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "D:\anaconda3\lib\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "D:\anaconda3\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 27, in init
    browser = await get_browser(**kwargs)
  File "D:\anaconda3\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 40, in get_browser
    return _browser or await init(**kwargs)
  File "D:\anaconda3\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 26, in init
    _playwright = await async_playwright().start()
  File "D:\anaconda3\lib\site-packages\playwright\async_api\_context_manager.py", line 51, in start
    return await self.__aenter__()
  File "D:\anaconda3\lib\site-packages\playwright\async_api\_context_manager.py", line 46, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "D:\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 181, in run
    await self._transport.connect()
  File "D:\anaconda3\lib\site-packages\playwright\_impl\_transport.py", line 136, in connect
    raise exc
  File "D:\anaconda3\lib\site-packages\playwright\_impl\_transport.py", line 124, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "D:\anaconda3\lib\asyncio\subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "D:\anaconda3\lib\asyncio\base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "D:\anaconda3\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

05-04 00:02:22 [ERROR] uvicorn | Application startup failed. Exiting.

Process finished with exit code 3

**Comment by MeetWq** [comment]
你的 nonebot_plugin_htmlrender 是什么版本的

**Comment by Amoslzh** [comment]
刚刚试了下 中国象棋插件是能运行的

**Comment by MeetWq** [comment]
你有没有改过 nonebot 配置文件中 fastapi 相关的设置？
需要确保 `fastapi_reload` 为 `False`
参考：https://v2.nonebot.dev/docs/tutorial/choose-driver#fastapi_reload

**Comment by Amoslzh** [comment]
我的env.dev里没有和fastapi有关的设置，那我是不是要在里面加
DRIVER=~fastapi
fastapi_reload=False

**Comment by Amoslzh** [comment]
我用的是真寻的机器人 估计是和里面什么插件冲突了

**Comment by MeetWq** [comment]
应该是 bilibili_api 的问题
可以先别加载B站相关的插件试试

**Comment by MeetWq** [comment]
https://github.com/HibiKier/zhenxun_bot/commit/31cdabc229eebca1461d13ae89039765a62c03c1
真寻那边已经有pr把bilibili_api去掉了，更新后理论上应该没问题了
